image: daewok/lisp-devel

stages:
  - build

before_script:
  - apt-get update -qy
  - apt-get install -y git-core
  - cp /builds/ediethelm/trivial-utilities ~/quicklisp/local-projects/
  - ls ~/quicklisp/local-projects/

build:
  stage: build
  script:
    - sbcl --non-interactive -e '(ql:quickload :trivial-utilities)'
    - exit /b %errorlevel%
